services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: peterssdb
      POSTGRES_USER: peter
      POSTGRES_PASSWORD: password123
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [appnet]

  api:
    build:
      context: ./server      
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__Default: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on: [db]
    networks: [appnet]


  web:
    image: caddy:2
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frontend/dist:/srv:ro
    depends_on: [api]
    networks: [appnet]

volumes:
  db_data:

networks:
  appnet:
